In [1]:
# Step1. NumPyをインポートするコードを記述する
import numpy as np

In [10]:
# Step2. AとBの行列を格納する多次元配列のコードを記述する
a = np.array([[0, 1], [2, 3], [4, 5]])
b = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])

In [12]:
# Step3. 行列の積の計算をするコードを記述する
c = np.dot(a, b)

In [13]:
# Step4. Step3.の計算結果を表示するコードを記述する
print(c)

[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]


In [18]:
# Step5. 行列の要素の最大値を求めるコードを記述する
c.max()

47